spring:
  application:
    name: "PiMall"
    version: "1.0.0"
    url: http://localhost:${server.port:8080}${server.servlet.context-path:}
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://192.168.0.108:3306/snowy?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true"
    username: "root"
    password: "123456"
  data:
    redis:
      host: "192.168.0.108"
      port: 6379
      database: 0
      #username: ""
      #password: ""
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false
  flyway:
    enabled: false
logging:
  level:
    root: "info"
    org.springframework.web: "debug"
    com.project: "debug"

# Pi配置
pi:
  # 秘钥
  api-key: "qxelfh6nt7opdfr7ui404tii4xah7fcjlh9mttgz5vjt99pkjgibjfd9yde56qr3"
  # 汇率 ( 人民币 * scale = Pi 币 )
  exchange-rate: 1
  # 小数点位数
  scale: 8
  # 调试模式: 正式环境关闭调试模式, 本地开发时打开(使用vpn访问PiApi接口)
  debug: true # TODO: 开发时打开注释
  # 代理主机
  proxy-hostname: 127.0.0.1
  # 代理端口
  proxy-port: 7897
